=== govtmirror/Video-Frame-Analyzer/bin/samma.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSpy v2011 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:complexType name="condition">
		<xs:annotation>
			<xs:documentation>Contains a condition that will be evaluated.  If multiple conditions exist, they are ANDed together..</xs:documentation>
		</xs:annotation>
		<xs:attribute name="LTE" type="xs:decimal">
			<xs:annotation>
				<xs:documentation>Less than or equal test</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="LT" type="xs:decimal">
			<xs:annotation>
				<xs:documentation>Less than test</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="GTE" type="xs:decimal">
			<xs:annotation>
				<xs:documentation>Greater than or equal test</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="GT" type="xs:decimal">
			<xs:annotation>
				<xs:documentation>Greater than test</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="EQ" type="xs:decimal">
			<xs:annotation>
				<xs:documentation>Equals test</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="NEQ" type="xs:decimal">
			<xs:annotation>
				<xs:documentation>Not equals test</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:element name="doc">
		<xs:annotation>
			<xs:documentation>Container element containing 0 or more test suites that may be chosen from the GUI.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="analysis-set" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="test" type="xs:boolean" default="false">
				<xs:annotation>
					<xs:documentation>This attribute is for development purposes only.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="analysis-set">
		<xs:annotation>
			<xs:documentation>Test suite that can be chosen via the GUI.  The first occurrence is the default selection in the GUI.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="analysis" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="purpose" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>Descriptive text to distinguish this test suite from other test suites.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="name" type="xs:normalizedString" use="required">
				<xs:annotation>
					<xs:documentation>Shorthand name for a test suite.  This was more applicable when running the command live version of the application.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="analysis">
		<xs:annotation>
			<xs:documentation>Definition of a specific test to execute.  A column will be added to the SAMMA Analysis report for each analysis element present in the chosen analysis set.  File Value tests evaluate a single property of the output file.  Other tests analyze the frame level attributes found within the SAMMA XML file.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:choice>
				<xs:sequence>
					<xs:element name="average" minOccurs="0">
						<xs:annotation>
							<xs:documentation>When running an average analysis, this defines the duration to use for analysis.</xs:documentation>
						</xs:annotation>
						<xs:complexType>
							<xs:attribute name="secs" type="xs:integer" use="required"/>
						</xs:complexType>
					</xs:element>
					<xs:element name="checkValid" type="condition">
						<xs:annotation>
							<xs:documentation>Condition that must be true for an analysis to pass (excluding range considerations).</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="checkFatal" type="condition">
						<xs:annotation>
							<xs:documentation>Condition, if present, which triggers a failure regardless of the range in which it occurs.</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="checkRangeError">
						<xs:annotation>
							<xs:documentation>Qualifications of the ranges in which the validity test will be performed</xs:documentation>
						</xs:annotation>
						<xs:complexType>
							<xs:attribute name="skipLast" type="xs:boolean">
								<xs:annotation>
									<xs:documentation>If true, exclude the final range of frames from the validity check.  Any conditions found in the last frame range will be reported as a warning.</xs:documentation>
								</xs:annotation>
							</xs:attribute>
							<xs:attribute name="skipFirstSec" type="xs:integer">
								<xs:annotation>
									<xs:documentation>If set, exclude the first X seconds of the file from the validity check.  Any conditions found in the first X seconds will be reported as a warning.</xs:documentation>
								</xs:annotation>
							</xs:attribute>
							<xs:attribute name="return" type="xs:boolean">
								<xs:annotation>
									<xs:documentation>This no longer appears to be used.  (TODO: test and remove)</xs:documentation>
								</xs:annotation>
							</xs:attribute>
							<xs:attribute name="minLenSec" type="xs:integer">
								<xs:annotation>
									<xs:documentation>Minimum frame duration in which a condition will be subject to a validity check.  Otherwise, the check will be reported as a warning.</xs:documentation>
								</xs:annotation>
							</xs:attribute>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
				<xs:sequence>
					<xs:element name="fileValue">
						<xs:annotation>
							<xs:documentation>Perform a test based on a single file level value rather than on a frame level value.</xs:documentation>
						</xs:annotation>
						<xs:complexType>
							<xs:attribute name="xpath" type="xs:string" use="required">
								<xs:annotation>
									<xs:documentation>XPATH expression pointing to the value to evaluate.</xs:documentation>
								</xs:annotation>
							</xs:attribute>
							<xs:attribute name="format">
								<xs:annotation>
									<xs:documentation>Value, if present, that will report a frame count as a time value.</xs:documentation>
								</xs:annotation>
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="time"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:complexType>
					</xs:element>
					<xs:element name="checkFile" type="condition">
						<xs:annotation>
							<xs:documentation>Defines the test to be performed on a specific file level value.</xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
			</xs:choice>
			<xs:attribute name="type" default="XmlAnalysis">
				<xs:annotation>
					<xs:documentation>Defines the type of analysis to perform.  If custom coding is done, additional types of analysis should be registered here.  The default value is XmlAnalysis which is a frame attribute test.  A PassFailAnalysis is a single value test.  An AverageAnalysis examines the average over a range of frames.</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="XmlAnalysis"/>
						<xs:enumeration value="AverageAnalysis"/>
						<xs:enumeration value="PassFailAnalysis"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="name" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>Description of the field being analyzed (displays in the report header)/</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="code" type="xs:normalizedString">
				<xs:annotation>
					<xs:documentation>SAMMA frame level "attribute" to be analyzed. </xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== govtmirror/Video-Frame-Analyzer/bin/DefaultAnalysis.xml
<?xml version="1.0" encoding="UTF-8"?>
<doc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="samma.xsd">
	<analysis-set name="no-luma" purpose="All rules except Luma">
		<analysis name="SampleCount" type="PassFailAnalysis">
			<fileValue format="time" xpath="/SammaSolo/Metadata/Log/SampleCount"/>
			<checkFile GT="3600"/>
		</analysis>
		<analysis code="DN" name="DOC Number" type="AverageAnalysis">
			<average secs="10"/>
			<checkValid LT="20"/>
			<checkFatal/>
			<checkRangeError skipLast="false"/>
		</analysis>
		<analysis code="RF" name="RF Level" type="XmlAnalysis">
			<checkValid GT="63.75"/>
			<checkFatal/>
			<checkRangeError minLenSec="1" skipFirstSec="30" skipLast="true"/>
		</analysis>
	</analysis-set>
	<analysis-set name="200-UN" purpose="No luma and allows for 10 seconds of dropout and low RF">
		<analysis code="DN" name="DOC Number" type="AverageAnalysis">
			<average secs="10"/>
			<checkValid LT="20"/>
			<checkFatal/>
			<checkRangeError/>
		</analysis>
		<analysis code="RF" name="RF Level">
			<checkValid GT="63.75"/>
			<checkFatal/>
			<checkRangeError minLenSec="10" skipFirstSec="30" skipLast="true"/>
		</analysis>
		<analysis name="SampleCount" type="PassFailAnalysis">
			<fileValue format="time" xpath="/SammaSolo/Metadata/Log/SampleCount"/>
			<checkFile GT="3600"/>
		</analysis>
	</analysis-set>
	<analysis-set name="none" purpose="Run no tests">
	</analysis-set>
	<analysis-set name="default" purpose="Default rules defined when analysis program was created.">
		<analysis code="DN" name="DOC Number" type="AverageAnalysis">
			<average secs="2"/>
			<checkValid LT="20"/>
			<checkFatal/>
			<checkRangeError skipLast="false"/>
		</analysis>
		<analysis code="RF" name="RF Level" type="XmlAnalysis">
			<checkValid GT="63.75"/>
			<checkFatal/>
			<checkRangeError minLenSec="1" skipFirstSec="30" skipLast="true"/>
		</analysis>
		<analysis code="LA" name="Luma Average" type="XmlAnalysis">
			<checkValid GTE="15"/>
			<checkFatal/>
			<checkRangeError minLenSec="180" skipLast="false"/>
		</analysis>
		<analysis code="LA" name="Luma Average" type="XmlAnalysis">
			<checkValid LTE="235"/>
			<checkFatal/>
			<checkRangeError minLenSec="5" skipLast="false"/>
		</analysis>
		<analysis name="SampleCount" type="PassFailAnalysis">
			<fileValue format="time" xpath="/SammaSolo/Metadata/Log/SampleCount"/>
			<checkFile GT="3600"/>
		</analysis>
	</analysis-set>
	<analysis-set name="slates" purpose="identify slates in file">
		<analysis code="LA" name="Luma Average">
			<checkValid LTE="15"/>
			<checkFatal/>
			<checkRangeError minLenSec="10"/>
		</analysis>
		<analysis name="SampleCount" type="PassFailAnalysis">
			<fileValue format="time" xpath="/SammaSolo/Metadata/Log/SampleCount"/>
			<checkFile GT="36000"/>
		</analysis>
	</analysis-set>
	<analysis-set name="twenty" purpose="At least twenty seconds">
		
	</analysis-set>
</doc>
